repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        - id: check-yaml
        - id: check-xml
        - id: check-ast
        - id: check-json
        - id: check-toml
        - id: debug-statements
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-merge-conflict
        - id: no-commit-to-branch
          args: [--branch, main, --branch, dev]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
        - id: black
          additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
        - id: isort
          args: ["--profile", "black"]
