# Generated by Django 4.2.6 on 2023-10-31 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("rss_url", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Date added to database"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(verbose_name="Last time the feed was checked"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "date_posted",
                    models.DateTimeField(verbose_name="Date posted to the remote feed"),
                ),
                ("seen", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_items.newssource",
                    ),
                ),
            ],
        ),
    ]
